Extracting common mustache template
51Degrees/pipeline-java pull request #28
Opened 2023-10-27 16:30 UTC by Riabkov

- Update JavaScriptResource.mustache
- Cleanup JavaScriptBuilderElement
- Add missing properties to JavaScriptResource
- Add missing properties setup to JavaScriptBuilderElement
- Upgrade mustache compiler version to 0.9.11

- Catch PropertyMissingException in JavaScriptBuilderElement
- Add unit tests in JavaScriptBuilderTests
- Remove stored mustache template

- Add submodule with javascript template

2023-11-02 15:00 UTC, justadreamer requested changes

2023-11-02 15:00 UTC, justadreamer commented on pipeline.javascriptbuilder/src/main/java/fiftyone/pipeline/javascriptbuilder/templates/JavaScriptResource.java
> +    private final String _sessionId;
so we've added these parameters: sessionId, sequence, parameters, but
a) there are no tests covering this logic.  
b) there is no logic in `JavascriptBuilderElement` passing these here.

Let's look at dotnet implementation and also [spec](https://github.com/51Degrees/specifications/blob/36ff732360acb49221dc81237281264dac4eb897/pipeline-specification/pipeline-elements/javascript-builder.md) on how to implement these

2023-11-02 15:00 UTC, justadreamer commented on pipeline.javascriptbuilder/src/main/java/fiftyone/pipeline/javascriptbuilder/Constants.java
> +    public static final String TEMPLATE = "/fiftyone/pipeline/javascriptbuilder/javascript-templates/JavaScriptResource.mustache";
do we need to rename the directory?  I think we can specify that the submodule checks out in the `template` directory, but that's cosmetical I guess

2023-11-02 15:01 UTC, justadreamer commented
Also please find a way to build a dev version of `pipeline-java` packages and to use them with `device-detection-java-examples` - so that the new Javascript template can be used with the cloud and onpremise examples.

2023-11-02 15:10 UTC, Riabkov commented on pipeline.javascriptbuilder/src/test/java/fiftyone/pipeline/javascriptbuilder/JavaScriptBuilderTests.java
> +        options.setAcceptInsecureCerts(true);
Added that from .NET just in case

2023-11-03 15:51 UTC, justadreamer approved these changes

2023-11-06 08:48 UTC, merged